### ISSUE TITLE
PWA cannot be installed

### ISSUE THREAD

**Issue by jmjurado23** [DannyMoerkerke/whatpwacando.today#1]
Hi, I am trying your app and I can not install the pwa either phone or desktop. I analize it in desktop chrome and the problem is that manifest is erroneous due to lost icons. I don't know if this it is the main problem or there are other. For this problem is your server which return a 403 when chrome try to bring the images. Check your server configuration or routes to solve the problem.

Thanks for your work!

**Comment by DannyMoerkerke** [comment]
Which files are missing exactly? And what device and platform are you using?

**Comment by jmjurado23** [comment]
Failed to load resource: the server responded with a status of 403 ()
Error while trying to use the following icon from the Manifest: https://whatpwacando.today/test/manifest-icon-192.png (Download error or resource isn't a valid image)

**Comment by DannyMoerkerke** [comment]
Yes I can reproduce it now.

**Comment by DannyMoerkerke** [comment]
Fix is deployed now, can you please check?

**Comment by jmjurado23** [comment]
Now I can install it perfectly!! Thanks!!!

**Comment by DannyMoerkerke** [comment]
Great, thanks for reporting!
