### ISSUE TITLE
Looks like PWA can't do nothing without JS :(

### ISSUE THREAD

**Issue by long-lazuli** [DannyMoerkerke/whatpwacando.today#10]
could this website benefit from SSR ?
or at least, showing a page describing benefits of allowing JS for this page...

![image](https://user-images.githubusercontent.com/1178625/102610008-c1c1c480-412c-11eb-9c66-9862f79bf229.png)

**Comment by DannyMoerkerke** [comment]
Long overdue, but this has now been added. Thanks for reporting!
