### ISSUE TITLE
No service worker detected

### ISSUE THREAD

**Issue by stl1988** [DannyMoerkerke/whatpwacando.today#11]
![image](https://user-images.githubusercontent.com/35177539/107324865-0ae92180-6aa9-11eb-8b95-b81f8b51fe3b.png)
It seems something is not right with the service worker. That's also why there is no install prompt.

**Comment by DannyMoerkerke** [comment]
I do have both and install prompt and the install icon in the address bar in Brave on MacOS.
Brave Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (x86_64).

Could you check in the Network tab if the service worker is downloaded or maybe clear the cache and reload the page?

![Screenshot 2021-02-09 at 09 21 33](https://user-images.githubusercontent.com/1424444/107336050-f9a81100-6ab8-11eb-8814-43a400915b48.png)

**Comment by DannyMoerkerke** [comment]
@stl1988 could you please check with my suggestion above?

**Comment by stl1988** [comment]
Did try it, but the install button is still grayed out and no install prompt appears in Brave. It does, however, work perfectly in Chromium based Edge and in Google Chrome. (Windows 10)

**Comment by stl1988** [comment]
Error from console in Brave:
[ServiceWorker] Install  service-worker.js:112
Uncaught (in promise) TypeError: Failed to fetch  service-worker.js:1

**Comment by DannyMoerkerke** [comment]
Which version of Brave is this?
Could you copy some more of this error message?
Is there a file in the Network tab that is not loaded?

**Comment by DannyMoerkerke** [comment]
Closed due to inactivity
