### ISSUE TITLE
CORS breaking on auth demo

### ISSUE THREAD

**Issue by daweimau** [DannyMoerkerke/whatpwacando.today#12]
Pressing "Register Credential" button at https://whatpwacando.today/authentication  yeilds "Registration failed" popup message.

In console this presents as a CORS problem:

```Access to fetch at 'https://api.whatpwacando.today/webauthn/registration-options' from origin 'https://whatpwacando.today' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

**Comment by DannyMoerkerke** [comment]
Thanks a lot for reporting!
This was due to a misconfiguration in the backend and has now been fixed.

Thanks!
