### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by johndavemanuel** [DannyMoerkerke/whatpwacando.today#13]
Is there any chance that this project become open source?

**Comment by DannyMoerkerke** [comment]
Hi John, I'm working on it.

**Comment by Hacksore** [comment]
Are there still plans to open source the project?

![staring cat](https://github.com/DannyMoerkerke/whatpwacando.today/assets/996134/da33188e-f5d2-4ef1-9255-28048ed0e661)
