### ISSUE TITLE
Main page misleading

### ISSUE THREAD

**Issue by Badlapje** [DannyMoerkerke/whatpwacando.today#16]
Would be cool if the main page would immediately give info for each feature which browsers support it.  After clicking three features i lost interest in checking because i figured while a feature may be technically possible in a browser today, that's not the same as saying this is something a PWA can do.  I interpret the latter as at least available in chromium browsers / firefox / safari.

**Comment by DannyMoerkerke** [comment]
A PWA can be installed through either of the browsers you mention after which it will be run as a PWA "through" that browser. 
It's not a requirement that a PWA must be installed through all those browsers so this is in fact what a PWA can do.

While I agree it would be ideal if all browsers would support the same features, that unfortunately is not the case but it's not a requirement either.
