### ISSUE TITLE
Voice recognition works in Safari on iOS but not when PWA is "added to home screen".

### ISSUE THREAD

**Issue by sgalzin** [DannyMoerkerke/whatpwacando.today#17]
The voice recognition demo works on Safari / iOS  (15.1). But when I "install" the PWA by adding it to the desktop, the fullscreen mode of the web site does not enable voice recognition anymore. There is not request for user authorization regarding the microphone, nothing happens.

**Comment by DannyMoerkerke** [comment]
It seems that voice recognition no longer works when a PWA is installed on iOS.
I will investigate, thanks.

**Comment by DannyMoerkerke** [comment]
I confirm that voice recognition no longer works on iOS for PWAs. It works in Safari, tested on iOS 15.4.1.
