### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by pranjaldugar** [DannyMoerkerke/whatpwacando.today#18]
**Network type Bug**
Device: Android Phone
Issue: In network information page, network type is shown as 4g.
My connected network: WIFI (my celular data is turned off)

**Feature Suggestion**
"Copy To Clipboard",
I know it is a part of web development and not specific to PWA and from a very long time now, however since you have also added audio player, I think this could be included too.

Thanks for your work, it helps a lot.

**Comment by DannyMoerkerke** [comment]
Currently only ChromeOS supports NetworkInformation.type. The value reported in the demo comes from NetworkInformation.effectiveType.

I will update the demo to show both values and note where `type` is not supported yet.

**Comment by DannyMoerkerke** [comment]
Both `type` and `effectiveType` are now reported (where available).

I will add a demo for clipboard soon.
