### ISSUE TITLE
[Authentication] webauth protocol behind

### ISSUE THREAD

**Issue by GuillaumeUnice** [DannyMoerkerke/whatpwacando.today#19]
I ask for a bit of help and documentation around the implementation.
Where is the source code of it?

And how do you manage server side the kind of  attestation format (I'm referring to the attestationObject.fmt property) that could be 'fido-u2f', 'android-safetynet' etc.

Thanks for any help

**Comment by DannyMoerkerke** [comment]
I created a demo that you can find here: https://github.com/DannyMoerkerke/webauthn-demo 
So far, I haven't had to deal with the attestation object but it might be this is already handled by the library used in the demo.

**Comment by GuillaumeUnice** [comment]
Thank you so much you are the best!

I made search on my side and I confirm the fido2-lib is at the this point probably the most complete librabry to deal with the attestation object and formats.

**Comment by DannyMoerkerke** [comment]
Great!
Let me know if you have any questions.
