### ISSUE TITLE
Text on "Installing on iOS page" page hard to read

### ISSUE THREAD

**Issue by jeffslofish** [DannyMoerkerke/whatpwacando.today#2]
The background color is white and the text is light gray, making it hard to read.

![IMG_CB81C3A81614-1](https://user-images.githubusercontent.com/1240484/76723277-e901e600-6703-11ea-8c3f-da0701d41141.jpeg)

**Comment by DannyMoerkerke** [comment]
Fixed in latest version, thanks for reporting.
