### ISSUE TITLE
App UI seems outdated would like to contribute 

### ISSUE THREAD

**Issue by dharmeshgurnani** [DannyMoerkerke/whatpwacando.today#22]
Hello Danny,
I feel the UI seems outdated will there be any update to this app? I would also like to contribute to this project and add visual improvements.

Regards,
dharmeshgurnani

**Comment by DannyMoerkerke** [comment]
Sorry for the late reply and thanks for reaching out!

I plan to open-source this project soon but at the moment it's too integrated with backend code that should not be in the repo so I'm trying to fix that.

**Comment by dharmeshgurnani** [comment]
@DannyMoerkerke let me know in case any help needed 😄
