### ISSUE TITLE
Need your help or source.+-code

### ISSUE THREAD

**Issue by rlegorreta** [DannyMoerkerke/whatpwacando.today#23]
Excellent PWA example. We have a project that needs a PWA app with camera and geolocalization. 
Can you share your code o need your help?
We are using Vaadin (Hilla) PWA framework. Is it possible to use your example.

Could not send you an email for the app

**Comment by DannyMoerkerke** [comment]
Please send me a message through https://whatpwacando.today/info and I'll be happy to answer your questions.
