### ISSUE TITLE
Off-topic question about PWA

### ISSUE THREAD

**Issue by lcsjunior** [DannyMoerkerke/whatpwacando.today#25]
PWA is used a lot, is it worth it? I'm new to mobile dev and I developed an MVP in React Native, but due to several technological limitations I thought about switching to PWA, does it make sense?

**Comment by DannyMoerkerke** [comment]
Yes it usually makes sense but it depends on your situation.
Since this is the issues section, please send me a message through https://whatpwacando.today/info and I'll be happy to answer your questions.
