### ISSUE TITLE
Issues in Payment functionality

### ISSUE THREAD

**Issue by pamnanaimanish169** [DannyMoerkerke/whatpwacando.today#26]
Steps to reproduce:

- Go to https://whatpwacando.today/payment
- Click on Checkout
- Nothing happens

On opening the console, the following error occurs:

![image](https://user-images.githubusercontent.com/21191012/198535524-82781939-368a-4f23-8344-eb50326ebd75.png)

Device Info:

Operating System: Windows 10 version 10.0 (64-bit), or Windows Server 2016 or 2019 version 10.0 (64-bit)
True Operating System Core: Unknown. Detection not supported or is blocked by browser setting(s)/extension(s).
Browser: Chrome version 106.0.0.0 (64-bit) (Engine: Blink)
True Browser Core: Unknown. Detection not supported or is blocked by browser setting(s)/extension(s).

**Comment by DannyMoerkerke** [comment]
This is now fixed and 'basic-card' has been removed.
Thanks for reporting!
