### ISSUE TITLE
You miss share target capability 

### ISSUE THREAD

**Issue by AdelaFoofur82** [DannyMoerkerke/whatpwacando.today#27]
You could add the capability of having your PWA as a share target in opposition of use the share action

**Comment by DannyMoerkerke** [comment]
This is already implemented.
From the share demo you can select the app itself as the share target.
Currently it only accepts the data from the demo so you won't see it listed if, for example, you want to share a picture.

**Comment by igorlanko** [comment]
Hey is this still the case? I actually don't see in the share sheet when tapping Share from the installed app on iOS 17.2.

Thanks!

**Comment by DannyMoerkerke** [comment]
This is currently only supported on Android unfortunately.

**Comment by igorlanko** [comment]
Ah, I see. What a shame! Thanks for the reply, @DannyMoerkerke!
