### ISSUE TITLE
Notification feature not supported despite Push API and Web notifications activated on iOS

### ISSUE THREAD

**Issue by rija** [DannyMoerkerke/whatpwacando.today#29]
Hi, 

Safari 16.2 on iOS and iPadOS has an advanced setting to enable experimental features.
I’ve enabled these two:
* Push API
* Builtin Web Notifications

And was expecting the notification demo feature of this PWA to be enabled, but it isn’t.
Is there additional tech that’s needed that I either need to enable or aren’t supported yet in Safari, not even as experimental feature? Or are there hard-coding in this PWA preventing it working ? Or those two particular experimental features are vendor-prefixed?

Note: I’ve enabled the “Contact Picker API” experimental feature, and the corresponding demo feature in this PWA started working since then

**Comment by DannyMoerkerke** [comment]
Just like on MacOS Monterey, the Push API is listed in the experimental features but is not (fully) implemented yet.
On iOS this seems to be the case as well since it throws the same error as on Monterey before:

`AbortError: No connection to push daemon`

I expect the Push API to be fully implemented only in iOS 17.

**Comment by rija** [comment]
Thanks for replying @DannyMoerkerke !

I haven't thought of looking at the web inspector, so I did that now (after enabling both aforementioned features) and I got this error on iPadOS 16.2 :

```
[Error] Unhandled Promise Rejection: ReferenceError: Can't find variable: Notification
	(anonymous function) (bundle.6172a84b17634dde95ff.js:221:78254)
	asyncFunctionResume
```

which seems to indicate that it's the Notification API which is not quite there yet.
Either way, the effect is the same as your observation: can't do notifications on Safari yet.

**Comment by DannyMoerkerke** [comment]
Yes, the test assesses if the Notifications API is supported and that is also what the demo shows. There is no Web Push API or backend involved at the moment. When support lands in iOS I will implement a full demo including the server side.
