### ISSUE TITLE
Geolocation does not work on iOS 16.4.1 (a)

### ISSUE THREAD

**Issue by blama** [DannyMoerkerke/whatpwacando.today#32]
[Geolocation](https://whatpwacando.today/geolocation) does not work on iOS 16.4.1 (a).
I always get a "Your device does not have the permission to access GPS information. Please enable this in your device's settings".

It does not matter if I just open the webpage or as PWA (after "Add to home screen"). I never get asked if I want to allow geolocation. And different to notifications in PWA, I also can't see a "location" option in my System app settings to configure permissions.

**Comment by carliblaz** [comment]
This is probably sistem setting on your phone, search for location in your phone settings and select your browser. Change that setting to ask or allow. I noticed, that if location settings for browser are set to never, there is no permission prompt for location, even if JS requires current position or watch position.

**Comment by DannyMoerkerke** [comment]
As @carliblaz mentioned you need to go to your iPhone settings and then go to Privacy & Security > Location Services > Safari Websites and then select “Ask next time or when I share” or “While using the app”.
