### ISSUE TITLE
"Install to home screen" does not work in Firefox (FF 113.0.2, Win10)

### ISSUE THREAD

**Issue by blama** [DannyMoerkerke/whatpwacando.today#33]
"Install to home screen" does not work in Firefox (FF 113.0.2, Win10).
Instead, it shows the explanation how to add the page to the Home Screen on iOS. It does work in Chromium and Edge, though.
Also, the explanation window is not fully visible here.

![image](https://github.com/DannyMoerkerke/whatpwacando.today/assets/6358308/6f29c9b7-063a-4cfd-9cb8-118a6776176f)

**Comment by DannyMoerkerke** [comment]
Firefox currently doesn't support installing PWAs, I will update the instructions.

**Comment by DannyMoerkerke** [comment]
Instructions for each browser updated
