### ISSUE TITLE
The PWA features of push notification and geolocation is no longer working on mobile via Chromium browsers

### ISSUE THREAD

**Issue by eugbyte** [DannyMoerkerke/whatpwacando.today#34]
Currently installed app on Android 12. Tried running the app after installing via Chromium browsers - Chrome, Brave.

## Expected behavior on Chromium browser:
1. Pop up notification requesting for permission for geolocation / web push notification appears
2. The geolocation and web push notification feature work.

## Current behaviour:
1. Pop up notification requesting for permission does not appear.
2. Geolocation and web push notification does not work. geolocation shows an indefinite spinner. 

For some reason, the app is working fine if PWA is installed via the Firefox mobile browser.

**Comment by DannyMoerkerke** [comment]
Can you check if notification and geolocation are blocked in Chrome on your device?
In Chrome on Android these can be unblocked through Settings > Site settings:

![Screenshot_20230712_092707_Chrome](https://github.com/DannyMoerkerke/whatpwacando.today/assets/1424444/3781e3de-e03d-442a-885b-699ab1df0bc7)

Notifications can also be blocked on Android through the main settings, you need to make sure notifications are enabled for the PWA if you have installed it. If the app doesn't show up under "Recently sent" you need to click "more":
![Screenshot_20230712_092636_Settings](https://github.com/DannyMoerkerke/whatpwacando.today/assets/1424444/0a82c8f9-f52a-4405-be56-bf83158be81e)


I added a dialog that will show up when notifications are blocked but I cannot detect if notifications are set be not shown under Settings > Notifications in Chrome.

If geolocation is blocked you should see a dialog to inform you of this:

![Screenshot_20230712_092725_Chrome](https://github.com/DannyMoerkerke/whatpwacando.today/assets/1424444/41f3f33d-298e-4b07-b392-bf7d2e49fde1)

I tested this on Android 12.

**Comment by eugbyte** [comment]
Ok, it was a problem on my end.

I was using Brave browser, with "Brave Shield" enabled. Apparently it automatically hides all notifications for permissions.

As for Chrome, I suspect it is a similar issue.
