### ISSUE TITLE
Going back breaks the website

### ISSUE THREAD

**Issue by TheotimeSlow** [DannyMoerkerke/whatpwacando.today#35]
Happened to me in firefox 117.0.1 on ubuntu.

Steps :
- On the website go to any feature.
- Go back to homepage using browser button or mouse button

Result :
- Back to the homepage, I can't click on any feature or even scroll the page. Going to another tab like info does not fix the problem, I have to manually refresh the page.

**Comment by DannyMoerkerke** [comment]
Thanks for reporting. I just fixed the issue, can you check on your side?

**Comment by TheotimeSlow** [comment]
Fixed on my side ! :+1:
