### ISSUE TITLE
Screen Wake Lock works in Safari on iOS but not when PWA is "added to home screen"

### ISSUE THREAD

**Issue by guiporto** [DannyMoerkerke/whatpwacando.today#36]
I'm running iOS 17.0.2

**Comment by DannyMoerkerke** [comment]
This is a known issue and has been fixed in Webkit but unfortunately it still hasn't been implemented in Safari for PWAs (what Apple calls Home Screen Web Apps).
See this issue and in particular this comment from Jen Simmons from last week: https://bugs.webkit.org/show_bug.cgi?id=254545#c32
