### ISSUE TITLE
When will the source code be releaded?

### ISSUE THREAD

**Issue by NeoPrint3D** [DannyMoerkerke/whatpwacando.today#38]
so currently I saw the demonstration of the device orientation affecting the 3d cube and tried to replicate it using device motion and react three fiber,  but currently I can't find a way to get device motion API to work with any javascript frameworks

**Comment by DannyMoerkerke** [comment]
Can you be more specific? What issues do you run into?

**Comment by NeoPrint3D** [comment]
So my question is when making the what pwa can do today website. Did you used a JavaScript framework like svelte, react or Vue? If so, did you use a polyfill lib because any useDeviceMotion from each respective  framework does not work or is when accessing the device motion through the raw JavaScript APis on each respective framework.

**Comment by DannyMoerkerke** [comment]
I didn't use any framework so I don't know about what these provide.
For the demos I simply used `deviceorientation` event and `devicemotion` event:

https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event
https://developer.mozilla.org/en-US/docs/Web/API/Window/devicemotion_event

**Comment by NeoPrint3D** [comment]
Ok thanks I had a feeling it was the framework. I used device motion and device orientation in all frameworks,I guess it is the JavaScript frameworks
