### ISSUE TITLE
Code to check if app is installed

### ISSUE THREAD

**Issue by Bamuel** [DannyMoerkerke/whatpwacando.today#39]
The webpage is missing source code to check if Install to home screen is done/ and how todo it.
![image](https://github.com/DannyMoerkerke/whatpwacando.today/assets/6744113/da7e6d0d-0b8c-4319-b288-2ca76ee60ee4)

**Comment by DannyMoerkerke** [comment]
The app uses the `beforeinstallprompt` event, the docs on MDN contain an example:
https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent

**Comment by pixelbrackets** [comment]
Thanks for the link here. It would be nice to have this "Installation" as a Feature with description, demo, source code and doc links as well.
