### ISSUE TITLE
Media Capture and AR/VR stop working after app has been minimized 

### ISSUE THREAD

**Issue by jeffslofish** [DannyMoerkerke/whatpwacando.today#4]
"Media Capture" and "AR/VR" work the first time the app is run, but if I click the home button on my iOS device and then click the app again on the home screen, the Media Capture displays no video input (everything is black) and the AR/VR screen only show the robot and no video.

If I kill the app and then click the app on the home screen, both features resume working.

![IMG_6D58AF5CAA78-1](https://user-images.githubusercontent.com/1240484/76724315-ce317080-6707-11ea-8723-2f60662c7069.jpeg)
![IMG_82AABFD51508-1](https://user-images.githubusercontent.com/1240484/76724322-d25d8e00-6707-11ea-80f3-66f7fec77dd0.jpeg)

**Comment by DannyMoerkerke** [comment]
I managed to fix this when navigating to another page in the app. However, when the app is moved to the background (by pressing the home button or swiping to from the button up on an iPhone X or 11) the problem persists.
I now reset the video component when navigating away from the page, which means that all buttons are reset and a loaded video is discarded. 
I run this exact same code when the app is moved to the background but in that case I use the `visibilitychanged` event on `document` to detect this. 
This leads me to believe it's an iOS bug but I will investigate further.

**Comment by DannyMoerkerke** [comment]
Media capture is now restarted when the app is minimized. This is currently the only way to make sure it doesn't freeze.
I tested minimizing AR/VR on iOS 15.4.1 and it indeed shows the robot only after minimizing but if I tap the AR button it works again.
