### ISSUE TITLE
Geolocation iOS

### ISSUE THREAD

**Issue by donaldparker** [DannyMoerkerke/whatpwacando.today#41]
Loads in the browser but not in the PWA.

**Comment by DannyMoerkerke** [comment]
What do you mean?

**Comment by qn0361** [comment]
![image](https://github.com/DannyMoerkerke/whatpwacando.today/assets/14351311/ff2d1412-edf4-4902-a997-10953733f9f4) 


![image](https://github.com/DannyMoerkerke/whatpwacando.today/assets/14351311/d44dac57-48ef-4751-aa3c-de01dac61cad)

**Comment by DannyMoerkerke** [comment]
What platform, device and browser + version?

**Comment by qn0361** [comment]
in my case the solution was: https://stackoverflow.com/a/73566334
(change safari sites settings)

maybe it can help the issue's author too.

i would suggest to directly mention that in the message in the app. it's not so obvious that you should change safari geo settings – not the settings of whatpwacandotoday app nor enabling geo services in general.

i mean it becomes obvious when you think about how it works under the hood. but a little extra transparency won't hurt in my opinion.

**Comment by DannyMoerkerke** [comment]
Thanks for reporting, I'm currently investigating this. In your screen shot the dialog is shown when permission is denied but on my iOS device I notice there is nothing showing when Location Services for Safari websites is set to "Ask Next Time or When I Share".
When I then try in Safari, I do get the permission prompt and when I give permission the setting is automatically changed to "While Using the App" and after that it also works in the PWA.

In your solution, did you set a `timeout` in the `options` object for `navigator.geolocation.getCurrentPosition` and then `Promise.race` with a `setTimeout` with a slightly longer timeout?

**Comment by DannyMoerkerke** [comment]
@qn0361 I managed to fix the issue, can you please check on your side?

**Comment by DannyMoerkerke** [comment]
Issue fixed, no confirmation from OP
