### ISSUE TITLE
[iOS bug] iOS PWA does not support light/dark mode switching

### ISSUE THREAD

**Issue by siimots** [DannyMoerkerke/whatpwacando.today#42]
Changing light/dark mode works in Safari, but when you add app to home screen (PWA) then it does not work any more.

iOS 17.2

It is iOS PWA bug not [whatpwacando.today](https://github.com/DannyMoerkerke/whatpwacando.today) bug

**Comment by siimots** [comment]
If anyone has link to webkit bugzilla then it would be helpful to link here.

https://developer.apple.com/forums/thread/739154
https://old.reddit.com/r/webdev/comments/178073i/ios_17_bug_pwas_no_longer_react_to_darklight_mode/

**Comment by DannyMoerkerke** [comment]
Thanks for reporting, this is indeed an iOS bug. 
I filed a bug report: https://bugs.webkit.org/show_bug.cgi?id=266853

**Comment by DannyMoerkerke** [comment]
Closing this as this is a Webkit bug.
