### ISSUE TITLE
Can't receive notifications with a delay of more than 5s

### ISSUE THREAD

**Issue by tiezhudotwang** [DannyMoerkerke/whatpwacando.today#43]
I tested both on `Android Chrome (OnePlus 7 OxygenOS 12.1, Chrome 120.0.6099.145)` and `Windows 11 Edge (121.0.2277.49 beta (64 bit))`, and both fail to receive notifications for more than 5s. I don't know if it's a problem with my testing method, you can try it out~

**Comment by DannyMoerkerke** [comment]
Thanks for reporting. I limited the delay time for demo purposes but failed to mention this in the form. 
I added it now.
