### ISSUE TITLE
Show availability of all PWA capabilities visually on homepage for current browser

### ISSUE THREAD

**Issue by sethmlarson** [DannyMoerkerke/whatpwacando.today#44]
Love the site! I had a suggestion because I want to try this on all my devices:

Having to click into each capability takes a bunch of time, would be even better to be shown the status for the current browser visually using either colors, symbols, or both.

**Comment by DannyMoerkerke** [comment]
The problem with this is that some capabilities can be enabled by setting feature flags in the browser.
For example, contact picker, face detection and QR-code detection can currently all be enabled manually in Safari and this is noted on the corresponding demo pages.

Users that don't have this enabled and don't visit the demo page will then not know the feature can be enabled when it's shown on the home page that these capabilities are not available.
