### ISSUE TITLE
AR demo doesn’t work in safari

### ISSUE THREAD

**Issue by jkjustjoshing** [DannyMoerkerke/whatpwacando.today#46]
In safari on iOS 17-1-2 on an iPhone 12 mini, without installing the PWA, the AR robot demo briefly flashes an AR screen (0.5 seconds) that says “Zero kb” then it closes. 

https://github.com/DannyMoerkerke/whatpwacando.today/assets/813192/713b276e-389c-4f07-9993-aefebc74290c

**Comment by DannyMoerkerke** [comment]
The link to the AR model was broken, now fixed.
