### ISSUE TITLE
iOS 17.3 Safari says JavaScript disabled

### ISSUE THREAD

**Issue by nephix** [DannyMoerkerke/whatpwacando.today#49]
When going to https://whatpwacando.today on iOS 17.3 Safari the PWA says JavaScript is disabled, when it's enabled:

![IMG_3607](https://github.com/DannyMoerkerke/whatpwacando.today/assets/3169205/ec33d13c-7f0a-49d5-8ae3-10fdef634c5d)
![IMG_3608](https://github.com/DannyMoerkerke/whatpwacando.today/assets/3169205/636d84fb-2e13-4a7f-9953-cd86e4b3e554)

**Comment by DannyMoerkerke** [comment]
This could happen due to slow loading JavaScript as this was the default content that was replaced. 
I implemented SSG today so this is now fixed.
