### ISSUE TITLE
doesnt work when phone is not connected to interner

### ISSUE THREAD

**Issue by chrisjameslennon** [DannyMoerkerke/whatpwacando.today#5]
When I am in flight mode and open the app I get a "cannot connect to site" error message and the app doesnt open.

To support offline mode

I am using samsung S8

**Comment by DannyMoerkerke** [comment]
Hi Chris, thanks for reporting. 
Did you already open the app at least once before trying to open in offline?

**Comment by Gareth10jones** [comment]
I see the same issue, even after having opened the app, closing, disabling data then reopening.  Error displayed is:

_"FetchEvent.respondWith received an error: TypeError: The internet connection appears to be offline"._

Great idea by the way and very useful!

**Comment by DannyMoerkerke** [comment]
I’m not able to reproduce this so far. Even with a fresh install and only opening the home screen, then going offline, all pages load. 
Can you still reproduce or share the steps how to reproduce it?

**Comment by Gareth10jones** [comment]
Does this help... https://we.tl/t-ucXMTBckU3

**Comment by DannyMoerkerke** [comment]
Interesting... I am able to reproduce it now on iOS13.
This was working before so I'll check and get back to you.

**Comment by Gareth10jones** [comment]
Ok great.  Glad I can help and no pressure from my side, was just confirming what @cjlennon was reporting.

**Comment by DannyMoerkerke** [comment]
Fixed and now released!

**Comment by chrisjameslennon** [comment]
yup working now nice one!

**Comment by Gareth10jones** [comment]
working for me too! Cheers!
