### ISSUE TITLE
iOS notifications don't work

### ISSUE THREAD

**Issue by nephix** [DannyMoerkerke/whatpwacando.today#50]
iOS Safari supports web push notifications when added to home screen
But it doesn't seem to work on https://whatpwacando.today

https://github.com/DannyMoerkerke/whatpwacando.today/assets/3169205/997c0115-7bbc-4d99-a389-b520d9249ac4

**Comment by DannyMoerkerke** [comment]
Apparently this doesn't work in Simulator but it does work in the app itself.

https://github.com/DannyMoerkerke/whatpwacando.today/assets/1424444/6c516c06-40ed-4506-a1cd-d6dfd5e9c391
