### ISSUE TITLE
"Install to home screen" broken in Firefox

### ISSUE THREAD

**Issue by CodesInChaos** [DannyMoerkerke/whatpwacando.today#51]
Pressing "Install to home screen" in Firefox freezes the website. The following errors appears in the console:

> Uncaught TypeError: installDialog.querySelector(...) is null
>    <anonymous> https://whatpwacando.today/:1241
>    EventListener.handleEvent* https://whatpwacando.today/:1233
> whatpwacando.today:1241:23

I understand that Firefox can't install PWAs, but a proper error should be shown, and the page should remain usable.

I'm using Firefox 122.0, Desktop-Linux, uBlockOrigin is installed but disabled.

**Comment by DannyMoerkerke** [comment]
This is now fixed.
