### ISSUE TITLE
Empty home page (and bad rendering of menu) on iOS

### ISSUE THREAD

**Issue by TheWebartist** [DannyMoerkerke/whatpwacando.today#55]
The home page is empty and the menu is broken when I Launch the website on iOS from app icon.

If I go on other menu options I have a valid rendering of menu and a valid content loaded.

**Comment by DannyMoerkerke** [comment]
I’m not able to reproduce this.
Are you able to connect your device to a MacBook and inspect it to see if it throws any errors?

How did you go from an empty home page to other pages?

**Comment by TheWebartist** [comment]
Hi,
I don’t have a MacBook.
But today I don’t reproduce this bug.

I send you 2 screenshots (yesterday and today).

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Danny Moerkerke ***@***.***>
Envoyé : Friday, May 10, 2024 10:45:43 AM
À : DannyMoerkerke/whatpwacando.today ***@***.***>
Cc : Vincent Menant ***@***.***>; Author ***@***.***>
Objet : Re: [DannyMoerkerke/whatpwacando.today] Empty home page (and bad rendering of menu) on iOS (Issue #55)


I’m not able to reproduce this.
Are you able to connect your device to a MacBook and inspect it to see if it throws any errors?

**Comment by TheWebartist** [comment]
Sorry I can't reproduce this issue today (no update on my iPhone).
I have sent 2 screenshots by email.
I close the issue.
