### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by AnaelBonnafous** [DannyMoerkerke/whatpwacando.today#59]
Here are some typos I found while browsing your website :

## Home page "/"

![image](https://github.com/user-attachments/assets/e338e01b-d5d1-47fd-afe7-4793c4c0e26f)

"Speech recognition" instead of "Speech recogniton"

## Info page "/info"

![image](https://github.com/user-attachments/assets/2751009d-a224-450d-ab19-910ddefc9bf8)

"into an iOS" instead of "into and iOS"

## Notifications page "/notifications"

![image](https://github.com/user-attachments/assets/d4aa6e34-e085-4d76-8da5-35414e875b76)

"in the meantime" instead of "in the mean time"

## File Handling API page "/file-handling"

![image](https://github.com/user-attachments/assets/2249c620-453e-4d1d-9183-f08b2ae34be5)

"file types" instead of "files types"

## Barcode and QR code reader page "/barcode"

![image](https://github.com/user-attachments/assets/0fc708ba-bcc7-4bae-b050-c99c86904fce)

"using the camera" instead of "using your the camera"

## Face detection page "/face-detection"

![image](https://github.com/user-attachments/assets/0fc708ba-bcc7-4bae-b050-c99c86904fce)

"using the camera" instead of "using your the camera"

## Network information page "/network-info"

![image](https://github.com/user-attachments/assets/10087a28-562d-4c1c-9edc-754f5207a258)

"bandwidth" instead of "bandwith"

**Comment by DannyMoerkerke** [comment]
Thanks for reporting!

For someone who always claims he can spot a typo from a mile away, I guess I did a poor job ;-)

Fixed.
