### ISSUE TITLE
Installation via DuckDuckGo on Android

### ISSUE THREAD

**Issue by Berkmann18** [DannyMoerkerke/whatpwacando.today#6]
When I try to install the PWA (via the provided button) on a Samsung Galaxy S7 Edge phone (Android 8.0), it seems to not be doable and when I install the site on the home screen via the browser's options it results in a website shortcut unlike when I do that via Chrome.
Is this normal or a bug?

**Comment by DannyMoerkerke** [comment]
What exactly do you mean?
Do you get an error when you use the provided button?
And what browser options are you using and in which browser?

**Comment by Berkmann18** [comment]
> Do you get an error when you use the provided button?

No, when I use the DuckDuckGo browser app on Android, the button is disabled and the only I got to _install_ the PWA on the home screen was via the browser option "Add to Home" which leads to a different result than when doing that with Chrome (i.e. a standard website shortcut on a phone rather than a PWA you know).

**Comment by DannyMoerkerke** [comment]
The DuckDuckGo browser does not support installing a PWA yet.
