### ISSUE TITLE
Shape Detection API Barcode Scanning has stopped working in iOS 18

### ISSUE THREAD

**Issue by brandscill** [DannyMoerkerke/whatpwacando.today#60]
Barcode Scanning no longer seems to detect URLs in QR codes and offer to navigate to the website as of iOS 18.

Tested in iOS 17.6.1 and this is working correctly.

**Comment by DannyMoerkerke** [comment]
Thanks for reporting, unfortunately it stopped working indeed.
I filed a bug with the Webkit team: https://bugs.webkit.org/show_bug.cgi?id=281848
