### ISSUE TITLE
getUserMedia stops working when background on both iOS and Android when on PWA

### ISSUE THREAD

**Issue by clshortfuse** [DannyMoerkerke/whatpwacando.today#63]
I have a PWA application that does WebRTC calls. On iOS and Android the microphone will stop working when you put the PWA in the background. On Android it stops working after a few seconds. On iOS it's immediate.

Both Android and iOS work when you use the built-in browsers: Chrome and Safari, respectively.

* https://bugs.webkit.org/show_bug.cgi?id=226620
* https://issues.chromium.org/issues/374374232

**Comment by DannyMoerkerke** [comment]
Thanks for reporting the issues.
These are browser bugs that can't be fixed in What PWA Can Do Today so I close this for now.

**Comment by clshortfuse** [comment]
👍  I'm reporting it because I noticed that Wakelock also has issues as a PWA on Safari and is reported by the site.
