### ISSUE TITLE
Network info

### ISSUE THREAD

**Issue by Berkmann18** [DannyMoerkerke/whatpwacando.today#7]
I'm not sure if it's an API issue or something to do with this app, but whenever I on the "Network info" section on my phone or laptop (both connected to the wifi) I always get `4g` as the "Network type" and that seems odd 😕.

**Comment by DannyMoerkerke** [comment]
Currently, the only property exposed in Chrome is `navigator.connection.effectiveType` and its values can only be 'slow-2g', '2g', '3g', or '4g'.
`navigator.connection.type` can report `wifi` but is not yet supported.

https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/effectiveType

**Comment by Berkmann18** [comment]
I see, thanks for the info.
