### ISSUE TITLE
Send a notification not working

### ISSUE THREAD

**Issue by pferreirafabricio** [DannyMoerkerke/whatpwacando.today#9]
Hi!
I tried to test the notification functionality, but found these errors on the console:

![Error in send notifacation](https://user-images.githubusercontent.com/42717522/93488871-34789500-f8dd-11ea-81bb-6e75e7dbd173.png)

Errors:
```javascript
Uncaught (in promise) TypeError: Failed to execute 'showNotification' on 'ServiceWorkerRegistration': No active registration available on the ServiceWorkerRegistration.
    at i (bundle.970dbe147463ef20abbf.js:225)
    at HTMLElement.<anonymous> (bundle.970dbe147463ef20abbf.js:225)
```

```javascript
bundle.970dbe147463ef20abbf.js:225 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'showNotification' in undefined
    at i (bundle.970dbe147463ef20abbf.js:225)
    at HTMLElement.<anonymous> (bundle.970dbe147463ef20abbf.js:225)
```

**OBS:** I have already given permission to send the notification.

**Browser:** Microsft Edge
**Version:** 85.0.564.51

**Comment by DannyMoerkerke** [comment]
Thanks for reporting!
I have tried it as well in the same build of Edge on MacOS and there the dev tools report that a notification was shown but the actual notification itself is not visible.
This could be a MacOS specific bug, but in any case the error you reported doesn't show up.
I will investigate further to see if I can reproduce it.
Which OS are you on?

**Comment by pferreirafabricio** [comment]
Hi Danny! I'm using Windows 10.

**Comment by rubenheymans** [comment]
It's working for me on widows 10, chrome and egde. It's been a while maybe try to Clear site data / cache and try again?

**Comment by pferreirafabricio** [comment]
I tried again and now it works, thanks!
